# deploy.yaml
# Author: Your Name
# Description: GitHub Actions workflow to deploy Helm chart to Kubernetes.

name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: <namespace>
      REPO_URL: <registryURL>

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        registry: ${{ env.REPO_URL }}
        username: _json_key
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.x'

    - name: Deploy Helm Chart
      run: |
        ./scripts/setup_environment.sh
        ./scripts/helm_config.sh
      env:
        NAMESPACE: ${{ env.NAMESPACE }}
        JSON_KEY_FILE: configs/repo-key.json
        EMAIL: <email>
        REGISTRY_URL: ${{ env.REPO_URL }}
