# helmfile.yaml
# Author: Your Name
# Description: Helmfile to manage Helm releases.

helmDefaults:
  wait: true
  timeout: 300
  kubeContext: <your-kube-context>

repositories:
  - name: owl-charts
    url: https://github.com/your-username/your-charts-repo

releases:
  - name: owldq
    namespace: owldq
    chart: owl-charts/owldq
    version: "1.0.0"
    values:
      - configs/config.json
