# helmfile.yaml

repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

context: <your-cluster-context>  # Specify the target Kubernetes cluster context

releases:
  - name: cilium
    chart: cilium/cilium
    version: <cilium_version>  # Specify the version you want
    namespace: cilium-namespace  # Change to the desired namespace
    values:
      - cilium-values.yaml  # Contents of cilium-values.yaml file

  - name: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: <dashboard_version>  # Specify the version you want
    namespace: dashboard-namespace  # Change to the desired namespace
    values:
      - k8s-dashboard-values.yaml  # Contents of k8s-dashboard-values.yaml file
